version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: company_dt
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: company_data
    ports:
      - "5433:5432"
    volumes:
      - company_dt:/var/lib/postgresql/data

volumes:
  company_dt:
